[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = '10.0.0.75'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 50001
Protocol = 'http'
StartupMsg = 'RFRain REST device started'
Timeout = 5000
ConnectRetries = 20
Labels = ['rfid', 'rest']
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

[Logging]
EnableRemote = false
File = ''

# Pre-define Devices
[[DeviceList]]
  Name = 'IOTECH0A0B0C'
  Profile = 'RFRainSensor'
  Description = 'RFRain RFID sensor reader'
  Labels = [ 'RFID-sensor' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]

[Driver]
User="customer@iotechsys.com"
Password="customer@iotechsys.com!"
Company="iotechsys"
SessionKeyURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_sessionkey"
# StartMonitoringURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/start_monitoring_new_tags_history"
# GetTagsURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_latest_tags_history"
InvalidateURL="https://cd2.rfrain.com/rfrainapi.php/destroy_sessionkey"
StartAlertEngineURL="https://cd2.rfrain.com/rfrainapi.php/start_alert_engine"
StopAlertEngineURL="https://cd2.rfrain.com/rfrainapi.php/stop_alert_engine"
StartAlertURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/start_all_alerts"
StopAlertURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/stop_all_alerts"
DefineAlertGroupURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/define_alert_group"
ListAlertGroupURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/list_alert_groups"
DefineAlertURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/define_alert"
AddAlertAPIEntryToGroupURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/add_alert_api_entry_to_group"
AlertRecEndpointURL="http://10.0.0.75/foo"
GroupName="IOTechGroup"
